baseURL = "https://khranovsky.com/"
defaultContentLanguage = "en"
theme = "minimal"

[languages]
  [languages.en]
    languageCode = "en-us"
    title = "blog by Denis Khran"
    weight = 1
  [languages.ru]
    languageCode = "ru"
    title = "blog by Denis Khran"
    weight = 2

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    noClasses = true
    style = "tango"
